### ISSUE TITLE
CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by thorwebdev** [drmzio/feedback#1]
Heya, I was trying to test out https://www.widgetscripts.com/ here https://thorwebdev.github.io/widgetscripts-test/index.html but I'm running into this CORS issue:

![image](https://user-images.githubusercontent.com/5748289/137082690-89a9528c-85d2-4822-982d-d658fc6d0ee5.png)

**Comment by drmzio** [comment]
@thorwebdev Thank you for reporting this. I thought I had this resolved, guess not 😅 Typical CORS

**Comment by drmzio** [comment]
@thorwebdev Yeah I can reset it for you. Currently, since there's no domain verification yet, I decided to check if the request origin matches the domain registered. So it has to be exact.

**Comment by drmzio** [comment]
Yup, that was the issue. Fixed it 👍 try now
